export const PROPERTIES_LOADED = 'PROPERTIES_LOADED'
export const PROPERTY_LOADED = 'PROPERTY_LOADED'
export const PROPERTY_ERR = 'PROPERTY_ERR'


export const TESTIMONAILS_LOADED = 'TESTIMONAILS_LOADED'
export const TESTIMONAIL_LOADED = 'TESTIMONAIL_LOADED'
export const TESTIMONAIL_ERR = 'TESTIMONAIL_ERR'


export const SERVICES_LOADED = 'SERVICES_LOADED';
export const SERVICE_ERR = 'SERVICE_ERR'

export const MEMBERS_LOADED = 'MEMBERS_LOADED'
export const MEMBER_ERR = 'MEMBER_ERR'

export const PARTNERS_LOADED = 'PARTNERS_LOADED'
export const PARTNER_ERR = 'PARTNER_ERR'


export const ARTICLES_LOADED = 'ARTICLES_LOADED'
export const ARTICLE_LOADED = 'ARTICLE_LOADED'
export const ARTICLE_ERR = 'ARTICLE_ERR'

export const CATEGORIES_LOADED = 'CATEGORIES_LOADED'
export const CATEGORY_ERR = 'CATEGORY_ERR'

export const FILTER_SETTINGS_LOADED = 'FILTER_SETTINGS_LOADED'
export const FILTER_SETTINGS_ERR = 'FILTER_SETTINGS_ERR'


export const LANGUAGE_CHANGED = 'LANGUAGE_CHANGED'


export const CITIES_LOADED = 'CITIES_LOADED'
export const CURRENCY_CHANGED = 'CURRENCY_CHANGED'
